---
# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: API Build

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
    paths:
      - 'api/**'
  pull_request:
    branches: [main]
    paths:
      - 'api/**'

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
