---
# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Vue Build

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
    paths:
      - 'client/**'
  pull_request:
    branches: [main]
    paths:
      - 'client/**'

env:
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESSRECORDINGKEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
  COMMIT_INFO_SHA: ${{ github.event.pull_request.head.sha }}

permissions: read-all

jobs:
  cypress-run-chrome:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true
          browser: chrome
          working-directory: client
          record: true
          tag: pr-component-chrome
